module:
  _merge: shallow
  imports:
    - path: github.com/spandigital/presidium-layouts-base
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: layouts
      target: layouts
params:
  _merge: shallow
  lazyLoad: false
  maxLeftNavMenuItems: 20
  minLeftNavMenuItems: 5
  articleTTLDays: 365
  favicon: images/favicon.ico
  archive:
    path: archive/index.md
  
