module:
  imports:
    - path: github.com/spandigital/presidium-layouts-base
  mounts:
    - source: assets
      target: assets
    - source: layouts
      target: layouts
params:
  lazyLoad: false
  slugifyUrl: false
  archive:
    path: archive/index.md
  favicon: images/favicon.ico
  
