module:
  imports:
    - path: github.com/spandigital/presidium-layouts-base
params:
  lazyLoad: false
  maxLeftNavMenuItems: 20
  minLeftNavMenuItems: 5
  articleTTLDays: 365
  favicon: images/favicon.ico
  archive:
    path: archive/_index.md
  frontmatter:
    - key: author
      type: email
      strict: true
    - key: date
      type: date
      strict: true
    - key: title
      type: text
      strict: true
    - key: description
      type: text
      strict: false
