module:
  imports:
    - path: github.com/spandigital/presidium-layouts-base
  mounts:
    - source: assets
      target: assets
    - source: layouts
      target: layouts
params:
  favicon: images/favicon.ico
